rvm:
  - 2.1
  - 2.2
  - 2.3

sudo: true

env:
  matrix:
# Split up the test-kitchen run to avoid exceeding 50 minutes:
  - KITCHEN_REGEXP=centos-72
  - KITCHEN_REGEXP=centos-68
  - KITCHEN_REGEXP=ubuntu-1604
  - KITCHEN_REGEXP=ubuntu-1404
  - KITCHEN_REGEXP=ubuntu-1204

before_script:
  - source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.5.0/scripts/start_docker.sh)

script:
  - travis_retry bundle exec rake integration:docker
