rvm:
  - 2.2
  - 2.3

sudo: required
services: docker

env:
  matrix:
# Split up the test-kitchen run to avoid exceeding 50 minutes:
  - KITCHEN_REGEXP=centos-72
  - KITCHEN_REGEXP=centos-68
  - KITCHEN_REGEXP=ubuntu-1604
  - KITCHEN_REGEXP=ubuntu-1404
  - KITCHEN_REGEXP=ubuntu-1204

# before_script:
#  - source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.5.0/scripts/start_docker.sh)

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.16
install: chef exec bundle install

script:
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml chef exec bundle exec kitchen verify ${KITCHEN_REGEXP}
